# home
reaccion_cms_admin_index:
    path: /
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\IndexController::index

# Pages
reaccion_cms_admin_pages_index:
    path: /pages
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\PageListController::index

reaccion_cms_admin_pages_create:
    path: /pages/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\CreatePageController::index

reaccion_cms_admin_pages_detail:
    path: /pages/{page}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\PageDetailController::index

reaccion_cms_admin_pages_remove:
    path: /pages/{page}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\RemovePageController::index

# Pages content
reaccion_cms_admin_create_page_content:
    path: /pages/{page}/content/add
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\CreatePageContentController::index

reaccion_cms_admin_edit_page_content:
    path: /pages/content/{content}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\PageContentDetailController::index

reaccion_cms_admin_remove_page_content:
    path: /pages/content/{content}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\RemovePageContentController::index

# Page translation groups
reaccion_cms_admin_create_page_translation_group:
    path: /pages/translation_group/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\TranslationGroups\CreateTranslationGroupController::index

reaccion_cms_admin_update_page_translation_group:
    path: /pages/translation_group/{pageTranslationGroup}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\TranslationGroups\PageTranslationGroupDetailController::index

reaccion_cms_admin_remove_page_translation_group:
    path: /pages/translation_group/{pageTranslationGroup}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\TranslationGroups\RemovePageTranslationGroupController::index

# Preferences
reaccion_cms_admin_preferences_configuration:
    path: /preferences/configuration
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\ConfigurationListController::index

reaccion_cms_admin_preferences_create_configuration:
    path: /preferences/configuration/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\CreateConfigurationController::index

reaccion_cms_admin_preferences_update_configuration:
    path: /preferences/configuration/{config}/update/
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\UpdateConfigurationController::index

reaccion_cms_admin_preferences_remove_configuration:
    path: /preferences/configuration/{config}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\RemoveConfigurationController::index

# Preferences > Mailer
reaccion_cms_admin_preferences_mailer:
    path: /preferences/mailer
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\Mailer\MailerConfigController::index

reaccion_cms_admin_preferences_mailer_sent_test_email:
    path: /preferences/mailer/send/test_email
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\Mailer\SendTestEmailController::index
    options:
        expose: true

# Preferences > Email templates
reaccion_cms_admin_preferences_email_templates:
    path: /preferences/email/templates
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\EmailTemplateController::index

reaccion_cms_admin_preferences_create_email_template:
    path: /preferences/email/templates/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\CreateEmailTemplateController::index

reaccion_cms_admin_preferences_update_email_template:
    path: /preferences/email/templates/{emailTemplate}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\UpdateEmailTemplateController::index

reaccion_cms_admin_preferences_remove_email_templates:
    path: /preferences/email/templates/{emailTemplate}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\RemoveEmailTemplateController::index

# Appearance > Menu
reaccion_cms_admin_appearance_menu:
    path: /appearance/menu
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuListController::index

reaccion_cms_admin_appearance_menu_create:
    path: /appearance/menu/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuCreateController::index

reaccion_cms_admin_appearance_menu_detail:
    path: /appearance/menu/{menu}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuDetailController::index

reaccion_cms_admin_appearance_menu_remove:
    path: /appearance/menu/{menu}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\RemoveMenuController::index

# Appearance > Menu > Content
reaccion_cms_admin_appearance_menu_content:
    path: /appearance/menu/{menu}/content
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuContentListController::index

reaccion_cms_admin_appearance_menu_content_create:
    path: /appearance/menu/{menu}/create/{parent}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuContentCreateController::index
    defaults:
        parent: 0

reaccion_cms_admin_appearance_menu_content_edit:
    path: /appearance/menu/{menu}/content/{menuContent}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuContentDetailController::index

reaccion_cms_admin_appearance_menu_content_remove:
    path: /appearance/menu/{menu}/remove/{menuContent}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\RemoveMenuContentController::index

reaccion_cms_admin_appearance_menu_content_update_position:
    path: /appearance/menu/{menu}/content/{menuContent}/{action}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\UpdateMenuContentPositionController::index

# Media
reaccion_cms_admin_media_index:
    path: /media
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaListController::index
    options:
        expose: true

reaccion_cms_admin_create_media:
    path: /media/add
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\CreateMediaController::index

reaccion_cms_admin_media_detail_by_path:
    path: /media/path
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaDetailController::findByPath
    options:
        expose: true

reaccion_cms_admin_media_detail:
    path: /media/{media}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaDetailController::index
    options:
        expose: true

reaccion_cms_admin_media_image_upload:
    path: /media/image/upload
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaImageUploadController::index
    options:
        expose: true

reaccion_cms_admin_remove_media:
    path: /media/{media}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\RemoveMediaController::index

# Users
reaccion_cms_admin_users_index:
    path: /users
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Users\UsersListController::index

reaccion_cms_admin_users_create:
    path: /users/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Users\CreateUserController::index

reaccion_cms_admin_users_update:
    path: /users/{user}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Users\UserEditController::index

# Entries > Categories
reaccion_cms_admin_entries_categories_list:
    path: /entries/categories
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\EntriesCategoriesListController::index

reaccion_cms_admin_entries_categories_create:
    path: /entries/categories/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\CreateEntriesCategoryController::index

reaccion_cms_admin_entries_categories_update:
    path: /entries/categories/{category}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\UpdateEntriesCategoryController::index

reaccion_cms_admin_entries_categories_remove:
    path: /entries/categories/{category}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\RemoveEntriesCategoryController::index

# Entries
reaccion_cms_admin_entries_list:
    path: /entries
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\EntriesListController::index

reaccion_cms_admin_entries_create:
    path: /entries/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\CreateEntryController::index

reaccion_cms_admin_entries_update:
    path: /entries/{entry}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\UpdateEntryController::index

reaccion_cms_admin_entries_remove:
    path: /entries/{entry}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\RemoveEntryController::index

# themes
reaccion_cms_admin_appearance_themes:
    path: /themes
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Themes\ThemesListController::index

reaccion_cms_admin_appearance_update_current_theme:
    path: /themes/update_current/{themeFolderName}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Themes\UpdateCurrentThemeController::index
