# Pages content
reaccion_cms_admin_create_page_content:
    path: /pages/{page}/content/add
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\CreatePageContentController::index

reaccion_cms_admin_edit_page_content:
    path: /pages/content/{content}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\PageContentDetailController::index

reaccion_cms_admin_remove_page_content:
    path: /pages/content/{content}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\RemovePageContentController::index

# Page translation groups
reaccion_cms_admin_create_page_translation_group:
    path: /pages/translation_group/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\TranslationGroups\CreateTranslationGroupController::index

reaccion_cms_admin_update_page_translation_group:
    path: /pages/translation_group/{pageTranslationGroup}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\TranslationGroups\PageTranslationGroupDetailController::index

reaccion_cms_admin_remove_page_translation_group:
    path: /pages/translation_group/{pageTranslationGroup}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\TranslationGroups\RemovePageTranslationGroupController::index

# Preferences
reaccion_cms_admin_preferences_configuration:
    path: /preferences/configuration
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\ConfigurationListController::index

reaccion_cms_admin_preferences_create_configuration:
    path: /preferences/configuration/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\CreateConfigurationController::index

reaccion_cms_admin_preferences_update_configuration:
    path: /preferences/configuration/{config}/update/
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\UpdateConfigurationController::index

reaccion_cms_admin_preferences_remove_configuration:
    path: /preferences/configuration/{config}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\RemoveConfigurationController::index

# Preferences > Mailer
reaccion_cms_admin_preferences_mailer:
    path: /preferences/mailer
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\Mailer\MailerConfigController::index

reaccion_cms_admin_preferences_mailer_sent_test_email:
    path: /preferences/mailer/send/test_email
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\Mailer\SendTestEmailController::index
    options:
        expose: true

# Preferences > Email templates
reaccion_cms_admin_preferences_email_templates:
    path: /preferences/email/templates
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\EmailTemplateController::index

reaccion_cms_admin_preferences_create_email_template:
    path: /preferences/email/templates/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\CreateEmailTemplateController::index

reaccion_cms_admin_preferences_update_email_template:
    path: /preferences/email/templates/{emailTemplate}/update
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\UpdateEmailTemplateController::index

reaccion_cms_admin_preferences_remove_email_templates:
    path: /preferences/email/templates/{emailTemplate}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EmailTemplates\RemoveEmailTemplateController::index

# Appearance > Menu
reaccion_cms_admin_appearance_menu:
    path: /appearance/menu
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuListController::index

reaccion_cms_admin_appearance_menu_create:
    path: /appearance/menu/create
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuCreateController::index

reaccion_cms_admin_appearance_menu_detail:
    path: /appearance/menu/{menu}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuDetailController::index

reaccion_cms_admin_appearance_menu_remove:
    path: /appearance/menu/{menu}/remove
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\RemoveMenuController::index

# Appearance > Menu > Content
reaccion_cms_admin_appearance_menu_content:
    path: /appearance/menu/{menu}/content
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuContentListController::index

reaccion_cms_admin_appearance_menu_content_create:
    path: /appearance/menu/{menu}/create/{parent}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuContentCreateController::index
    defaults:
        parent: 0

reaccion_cms_admin_appearance_menu_content_edit:
    path: /appearance/menu/{menu}/content/{menuContent}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuContentDetailController::index

reaccion_cms_admin_appearance_menu_content_remove:
    path: /appearance/menu/{menu}/remove/{menuContent}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\RemoveMenuContentController::index

reaccion_cms_admin_appearance_menu_content_update_position:
    path: /appearance/menu/{menu}/content/{menuContent}/{action}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\UpdateMenuContentPositionController::index

# themes
reaccion_cms_admin_appearance_themes:
    path: /themes
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Themes\ThemesListController::index

reaccion_cms_admin_appearance_update_current_theme:
    path: /themes/update_current/{themeFolderName}
    controller: ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Themes\UpdateCurrentThemeController::index
