# fos user
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# home
reaccion_cms_admin_index:
    path: /
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\IndexController::index

# Pages
reaccion_cms_admin_pages_index:
    path: /pages
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\PageListController::index

reaccion_cms_admin_pages_create:
    path: /pages/create
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\CreatePageController::index

reaccion_cms_admin_pages_detail:
    path: /pages/{page}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\PageDetailController::index

reaccion_cms_admin_pages_remove:
    path: /pages/{page}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\RemovePageController::index

# Pages content
reaccion_cms_admin_create_page_content:
    path: /pages/{page}/content/add
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\CreatePageContentController::index

reaccion_cms_admin_edit_page_content:
    path: /pages/content/{content}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\PageContentDetailController::index

reaccion_cms_admin_remove_page_content:
    path: /pages/content/{content}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\RemovePageContentController::index

# Preferences
reaccion_cms_admin_preferences_configuration:
    path: /preferences/configuration
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\ConfigurationListController::index

reaccion_cms_admin_preferences_create_configuration:
    path: /preferences/configuration/create
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\CreateConfigurationController::index

reaccion_cms_admin_preferences_update_configuration:
    path: /preferences/configuration/{config}/update/
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Configuration\UpdateConfigurationController::index

# Preferences > Menu
reaccion_cms_admin_preferences_menu:
    path: /preferences/menu
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuListController::index

reaccion_cms_admin_preferences_menu_create:
    path: /preferences/menu/create/{parent}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuCreateController::index
    defaults:
        parent: 0

reaccion_cms_admin_preferences_menu_edit:
    path: /preferences/menu/{menu}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\MenuDetailController::index

reaccion_cms_admin_preferences_menu_remove:
    path: /preferences/menu/{menu}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Menu\RemoveMenuController::index

# Media
reaccion_cms_admin_media_index:
    path: /media
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaListController::index
    options:
        expose: true

reaccion_cms_admin_create_media:
    path: /media/add
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\CreateMediaController::index

reaccion_cms_admin_media_detail_by_path:
    path: /media/path
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaDetailController::findByPath
    options:
        expose: true

reaccion_cms_admin_media_detail:
    path: /media/{media}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\MediaDetailController::index
    options:
        expose: true

reaccion_cms_admin_remove_media:
    path: /media/{media}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Media\RemoveMediaController::index

# Users
reaccion_cms_admin_users_index:
    path: /users
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Users\UsersListController::index

reaccion_cms_admin_users_create:
    path: /users/create
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Users\CreateUserController::index

reaccion_cms_admin_users_update:
    path: /users/{user}/update
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Users\UserEditController::index

# Entries > Categories
reaccion_cms_admin_entries_categories_list:
    path: /entries/categories
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\EntriesCategoriesListController::index

reaccion_cms_admin_entries_categories_create:
    path: /entries/categories/create
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\CreateEntriesCategoryController::index

reaccion_cms_admin_entries_categories_update:
    path: /entries/categories/{category}/update
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\UpdateEntriesCategoryController::index

reaccion_cms_admin_entries_categories_remove:
    path: /entries/categories/{category}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\EntriesCategories\RemoveEntriesCategoryController::index

# Entries
reaccion_cms_admin_entries_list:
    path: /entries
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\EntriesListController::index

reaccion_cms_admin_entries_create:
    path: /entries/create
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\CreateEntryController::index

reaccion_cms_admin_entries_update:
    path: /entries/{entry}/update
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Entries\UpdateEntryController::index