reaccion_cms_admin_index:
    path: /
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\IndexController::index

# Pages
reaccion_cms_admin_pages_index:
    path: /pages
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\PageListController::index

reaccion_cms_admin_pages_create:
    path: /pages/create
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\CreatePageController::index

reaccion_cms_admin_pages_detail:
    path: /pages/{page}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\PageDetailController::index

reaccion_cms_admin_pages_remove:
    path: /pages/{page}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\RemovePageController::index

# Pages content
reaccion_cms_admin_create_page_content:
    path: /pages/{page}/content/add
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\CreatePageContentController::index

reaccion_cms_admin_edit_page_content:
    path: /pages/content/{content}
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\PageContentDetailController::index

reaccion_cms_admin_remove_page_content:
    path: /pages/content/{content}/remove
    controller: App\ReaccionEstudio\ReaccionCMSAdminBundle\Controller\Pages\Content\RemovePageContentController::index